### ISSUE TITLE
[EPIC] Analytics Feature

### ISSUE THREAD

**Issue by callmekungfu** [KonomiAI/Chronicle#226]
> As a User, I want to be able to aggregate activity entry data, so I can gain business insights and better improve business processes

### Goals

- [ ] Generate tabular data based on attributes in activity entries
- [ ] Generate data using fixed fields in activity entries
- [ ] View all reports created in the organization

### MVP task
- [ ] Design system for creating analytics reports
- [ ] Implement necessary back-end services for creating and saving analytics reports
- [ ] Finalize MVP state UI for analytics reports in Figma
- [ ] Implement UI for analytics feature

### Goals

- [ ] Have automated report generation capabilities
- [ ] Generate data using custom forms in activity entries
- [ ] Export data to CSV files

**Comment by callmekungfu** [comment]
MVP completed
